## 3D plot of rule measurements

# Create Data frame of rules
eotb_rules_df = DATAFRAME(eotb_rules, separate = TRUE)

# x-axis title
axx = list(
  title = "Support"
)

# y-axis title
axy = list(
  title = "Confidence"
)

# z-axis title
axz = list(
  title = "Lift"
)

# Change colors for high values of each measurement
eotb_rules_df$color = ' '
eotb_rules_df$color[eotb_rules_df$support > .2] = 'High Support'
eotb_rules_df$color[eotb_rules_df$confidence > .9] = 'High Confidence'
eotb_rules_df$color[eotb_rules_df$lift > 4.5] = 'High Lift'
eotb_rules_df$color[eotb_rules_df$lift > 4.5 & eotb_rules_df$confidence > .9] = 'High Confidence & Lift'


# Create 3D visual with plotly
fig = plot_ly(eotb_rules_df, x = ~support, y = ~confidence, z = ~lift)
fig = fig %>% add_markers(color = ~color)
fig = fig %>% layout(title = '3D Plot of Association Rules',
                      scene = list(
                        xaxis = axx,
                        yaxis = axy,
                        zaxis = axz
                      ))
# View figure
fig


# Save as html widget
saveWidget(fig, "Association_Rules_3d_plot.html")
