---
title: "R Notebook"
output: html_notebook
---


## Import Libraries
```{r}
library(tidyverse)
library(plyr)
library(ggplot2)
library(factoextra)
library(GGally)
library(ggpubr)
library(lubridate)
library(cluster)
library(fpc)
library(dbscan)
library(plotly) 
library(ggdendro)
library(htmlwidgets)
library(philentropy)
```

## Import CSV file of cleaned data
```{r}
eotb = read.csv('EOTB_Cleaned.csv')

# Check structure of data to ensure all in proper format
#str(eotb)

#'X' column is a duplicate, remove it. 
eotb = eotb[,!(names(eotb) %in% 'X')]
# Data column was imported as a character, needs to be in date time. 
eotb$DateTime = lubridate::parse_date_time(eotb$DateTime, "ymd HMS")

# View data structure again
#str(eotb)
# Structure looks good now
```

## Subsetting data for clustering
```{r}
# Need only numeric data so will subset the data. 
# Due to size of data, subsetting dataset for just the span of a year 
num_eotb = eotb[(year(eotb$DateTime) > 2018 )& (year(eotb$DateTime) < 2020 ), 4:9]


# Then the data will need to be normalized
num_eotb = scale(num_eotb)
num_eotb = as.data.frame(num_eotb)
#class(num_eotb)
```
## Elbow Method
```{r}
# Data was too large to run Fviz so manually ran elbow method
set.seed(102)
wss = (nrow(num_eotb)-1)*sum(apply(num_eotb,2,var))
  for(i in 2:15){
    wss[i] = sum(kmeans(num_eotb,centers=i)$withinss)
  }
ggplot()+
  geom_point(aes(x = 1:15, y = wss, color = 'red'))+
  geom_line(aes(x = 1:15, y = wss))+
  labs(
  x = 'k',
  y = 'Sum of Squares',
  title = 'Elbow Plot for k clusters of the Water Quality Data Set')+
  theme(plot.title = element_text(size=17, face="bold", 
    margin = margin(10, 0, 10, 0),hjust =.5),
    legend.position = "none")+
  scale_x_continuous(breaks = 2:15)
ggsave('Elbow_all_data.png', width = 15, height = 10, dpi = 'retina')


```

```{r}
#  5, and 8 appear to be optimal number of clusters for dataset.
set.seed(102)
k = 8

# Now kmeans clustering 
clus = kmeans(num_eotb, centers = k)
```


```{r}
dat_clus = clus %>%
  fviz_cluster(data = num_eotb, show.clust.cent = TRUE,geom = 'point', pointsize = .1,ellipse = TRUE) + 
  theme(plot.title = element_text(size=17, 
                                  face="bold",
                                  margin = margin(10, 0, 10, 0),
                                  hjust =.5),
        panel.grid.minor.x = element_blank()) +
  
    labs( title = 'Clusters of 2019 Water Quality Data Subset')
ggsave('All_data_2019_clustk8.png', width = 15, height = 10, dpi = 'retina')


dat_clus

```

```{r}
# It is difficult to determine anything from this plot, the clusters largely appear to be very close to eachother with some outliers
# 3d plot of temp, salinity & ph
set.seed(102)
dat = data.frame(num_eotb$T_Fahr,num_eotb$Salinity_ppt,num_eotb$pH)
wss = (nrow(dat)-1)*sum(apply(dat,2,var))
for(i in 2:10){  
  wss[i] = sum(kmeans(dat,centers=i)$withinss)
}

ggplot()+
  geom_point(aes(x = 1:10, y = wss, color = 'red'))+
  geom_line(aes(x = 1:10, y = wss))+
  labs(
  x = 'k',
  y = 'Sum of Squares',
  title = 'Elbow Plot for k clusters of the Temperature, Salinity, and pH Variables')+
  theme(plot.title = element_text(size=17, face="bold", 
    margin = margin(10, 0, 10, 0),hjust =.5),
    legend.position = "none")+
  scale_x_continuous(breaks = 2:10)
ggsave('Elbow_sub_1.png', width = 15, height = 10, dpi = 'retina')


```
```{r}
# k = 4 seems like an optimal number for k
set.seed(102)

k = 4 
clus = kmeans(dat, centers = k)
dat$cluster = clus$cluster


axx <- list(
  title = "Temperature (F)"
)

axy <- list(
  title = "Salinity (ppt)"
)

axz <- list(
  title = "pH"
)
fig = plot_ly(x = dat$num_eotb.T_Fahr, y = dat$num_eotb.Salinity_ppt, z = dat$num_eotb.pH)
fig = fig %>%  
  add_markers(color = dat$cluster, size=.01) %>%
  layout(title = '3D Cluster Plot of Temperature, Salinity, and pH',
         scene = list(
           xaxis=axx,
           yaxis=axy, 
           zaxis=axz))
fig
saveWidget(fig, "clust2.html")


```

# Summarize data by taking mean during each month for hierarchical clustering 
```{r}
set.seed(102)
df = data.frame(matrix(ncol = 7, nrow = 0))

for (i in 1:12){
  dat = eotb[eotb$month_col==i,4:10]
  means = colMeans(dat)
  df = rbind(df,means)
}
# Get rid of month column, not actually numeric data
df = df[,1:6]
c_names = c('Salinity','pH','Dissolved Oxygen','Turbidity','Chlorophyll','Temperature')
colnames(df) = c_names

df = scale(df)

dist_eucl = dist(df, method = "euclidean")
dist_man = dist(df, method = "manhattan")
dist_cos <- distance(as.matrix(df), method="cosine",use.row.names = F)
dist_cos<- as.dist(dist_cos)
labels = c('1','2','3','4','5','6','7','8','9','10','11','12')

eucl_clust = hclust(dist_eucl, method = "ward.D2" )
man_clust = hclust(dist_man, method = "ward.D2" )
cos_clust = hclust(dist_cos, method = "ward.D2" )
cos_clust$labels = labels

eucl = ggdendrogram(eucl_clust)+
  labs(
  x = 'Months',
  y = 'Height',
  subtitle = 'Euclidean Distance Method',
  title = 'Dendogram of Monthly Average Water Quality Data')+
  theme(plot.title = element_text(size=17, face="bold", 
    margin = margin(10, 0, 10, 0),hjust =.5),
    plot.subtitle = element_text(hjust =.5))
ggsave('Euc_dist_dendo.png', width = 15, height = 10, dpi = 'retina')
eucl

man = ggdendrogram(man_clust)+
  labs(
  x = 'Months',
  y = 'Height',
  subtitle = 'Manhattan Distance Method',
  title = 'Dendogram of Monthly Average Water Quality Data')+
  theme(plot.title = element_text(size=17, face="bold", 
    margin = margin(10, 0, 10, 0),hjust =.5),
    plot.subtitle = element_text(hjust =.5))
ggsave('Man_dist_dendo.png', width = 15, height = 10, dpi = 'retina')
man

cosi = ggdendrogram(cos_clust)+
  labs(
  x = 'Months',
  y = 'Height',
  subtitle = 'Cosine Similarity Distance Method',
  title = 'Dendogram of Monthly Average Water Quality Data')+
  theme(plot.title = element_text(size=17, face="bold", 
    margin = margin(10, 0, 10, 0),hjust =.5),
    plot.subtitle = element_text(hjust =.5))
ggsave('Cos_dist_dendo.png', width = 15, height = 10, dpi = 'retina')
cosi



```

```{r}
set.seed(102)

dat = data.frame(num_eotb$Turb_NTU,num_eotb$DO_pctSat,num_eotb$pH)
wss = (nrow(dat)-1)*sum(apply(dat,2,var))
  for(i in 2:10)  wss[i] <- sum(kmeans(dat,
                                       centers=i)$withinss)
ggplot()+
  geom_point(aes(x = 1:10, y = wss, color = 'red'))+
  geom_line(aes(x = 1:10, y = wss))+
  labs(
  x = 'k',
  y = 'Sum of Squares',
  title = 'Elbow Plot for k clusters of the Temperature, Salinity, and pH Variables')+
  theme(plot.title = element_text(size=17, face="bold", 
    margin = margin(10, 0, 10, 0),hjust =.5),
    legend.position = "none")+
  scale_x_continuous(breaks = 2:10)
ggsave('Elbow_sub_2.png', width = 15, height = 10, dpi = 'retina')



```


```{r}
# k = 6 seems like an optimal number for k
set.seed(102)
k = 4
clus = kmeans(dat, centers = k, nstart = 25)
dat$cluster = clus$cluster


axx <- list(
  title = "Turbidity (NTU))"
)

axy <- list(
  title = "Dissolved Oxygen (% Saturation)"
)

axz <- list(
  title = "pH"
)
fig = plot_ly(x = dat$num_eotb.Turb_NTU, y = dat$num_eotb.DO_pctSat, z = dat$num_eotb.pH)
fig = fig %>%  
  add_markers(color = dat$cluster, size=.01) %>%
  layout(title = '3D Cluster Plot of Turbidity, Dissolved Oxygen, and pH',
         scene = list(
           xaxis=axx,
           yaxis=axy, 
           zaxis=axz))
fig

saveWidget(fig, "clust1.html")


```




