
## Creating Table of Confidence Values

eotb_rules_conf = sort(eotb_rules, by="confidence", decreasing=TRUE)
#inspect(eotb_rules_conf[1:20])

# Create dataframe with rules sorted by confidence
eotb_conf = DATAFRAME(eotb_rules_conf, separate = TRUE)

# Make rules more visually appealing
eotb_conf[] = lapply(eotb_conf, gsub, pattern='[{]', replacement='')
eotb_conf[] = lapply(eotb_conf, gsub, pattern='[}]', replacement='')
eotb_conf[] = lapply(eotb_conf, gsub, pattern='[_]', replacement=' ')
eotb_conf[] = lapply(eotb_conf, gsub, pattern='[,]', replacement=' & ')

# Get columns for table & change column names
eotb_conf = eotb_conf[,c('LHS','RHS','confidence','support','lift')]
colnames(eotb_conf) = c('Source','Target', 'Confidence','Support','Lift')

# Round numbers for table
eotb_conf[,3:5] = as.numeric(unlist(eotb_conf[,3:5]))
eotb_conf[,3:5] = round(eotb_conf[,3:5],3)

# Get top 15 rules
disp_conf = eotb_conf[1:15,]

# Don't show row names
row.names(disp_conf) = NULL

# Create table with gt package
conf = gt(disp_conf)
conf = conf %>%
  
  # Create title & Subtitle
  tab_header(
    title = 'Association Rules',
    subtitle = "Sorted by Confidence"
  ) %>%
  
  # Highlight Column of interest
  tab_style(
    style = cell_fill(color = "yellow"),
    locations = cells_body(
      columns = Confidence)) %>%
  
  # Show High support values
  tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(
      columns = Support,
      rows = Support > .1
    )
  )%>%
  
  # Show high lift values
  tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(
      columns = Lift,
      rows = Lift > 2
    )
  )%>%
  
  # Bold source where both lift and support are high
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(
      columns = Source,
      rows = (Support > .1 & Lift > 2)
  )) %>%
  
  # Bold target where both lift and support are high
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(
      columns = Target,
      rows = (Support > .1 & Lift > 2)))

conf
gtsave(conf,'confidence_table.html')