---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(lubridate)
library(GGally)
library(ggpubr)
library(randomcoloR)
library(reshape2)
library(ggplot2)
```

# Read in Data
```{r}
#dataset = read.csv('EOTB_Cleaned.csv')
dat = dataset
# Set to datetime again
dat$DateTime = lubridate::parse_date_time(dat$DateTime, "ymd HMS")

```

# Plot salinity over time
```{r}
p = ggplot()
p = p+  geom_point(data = dat[1:725000,], aes(y = Salinity_ppt[1:725000],x = DateTime[1:725000], color = 'darkred',alpha = 0.05))
p = p +  labs(
    x = 'Date',
    y = 'Salinity (ppt)',
    title = 'Salinity Over Time (2007 - 2011)'
  )
p = p +  theme(plot.title = element_text(size=17, face="bold",
    margin = margin(10, 0, 10, 0),hjust =.5),
    legend.position = "none",
    axis.text.x = element_text(angle = 90, vjust = 0.5))
p = p +  scale_x_datetime(date_breaks = "3 months", date_labels = "%m %Y")


ggsave(plot = p, filename = 'salinity_over_time.png')


```

# Plot boxplots of quantitative columns
```{r}


d <- melt(dat[,-c(1:4,11)])
ggplot(d,aes(x = value)) + 
    facet_wrap(~variable,scales = "free_x") + 
    geom_boxplot()
ggsave('var_box_plots.png')
```

# Plot histograms of pH at each recording station
```{r}
ggplot(dat, aes(x = pH,)) +
  geom_histogram(bins = 50, fill = 'dodgerblue') +       
  theme(plot.title = element_text(size=17, face="bold",
    margin = margin(10, 0, 10, 0),hjust =.5),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank())+
  labs(                                         
    x = "pH",
    y = "Frequency",
    title = "pH at Different Stations") +
  facet_wrap(~Station, scales = "free_y", ncol = 1) 
ggsave('hist_pH_stations.png',  dpi = 300)

```

